# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheel',
            old_name='track',
            new_name='trackid',
        ),
    ]
