# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_foodtypes_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtypes',
            name='typesort',
            field=models.IntegerField(default=1),
        ),
    ]
